{"pytest_version": "7.2.2", "$report_type": "SessionStart"}
{"nodeid": "tests29_98_4.py::test_list_of_prime_numbers", "location": ["tests29_98_4.py", 18, "test_list_of_prime_numbers"], "keywords": {"test_list_of_prime_numbers": 1, "tests29_98_4.py": 1, "Folder_98": 1}, "outcome": "passed", "longrepr": null, "when": "setup", "user_properties": [], "sections": [], "duration": 0.00015905400141491555, "$report_type": "TestReport", "item_index": 2, "worker_id": "gw1", "testrun_uid": "a8ecadee210e4e3190a9d4ede21af223", "node": "<WorkerController gw1>"}
{"nodeid": "tests29_98_4.py::test_list_of_ones", "location": ["tests29_98_4.py", 7, "test_list_of_ones"], "keywords": {"test_list_of_ones": 1, "tests29_98_4.py": 1, "Folder_98": 1}, "outcome": "passed", "longrepr": null, "when": "setup", "user_properties": [], "sections": [], "duration": 0.00017776000095182098, "$report_type": "TestReport", "item_index": 0, "worker_id": "gw0", "testrun_uid": "a8ecadee210e4e3190a9d4ede21af223", "node": "<WorkerController gw0>"}
{"nodeid": "tests29_98_4.py::test_list_of_ones", "location": ["tests29_98_4.py", 7, "test_list_of_ones"], "keywords": {"test_list_of_ones": 1, "tests29_98_4.py": 1, "Folder_98": 1}, "outcome": "failed", "longrepr": {"reprcrash": {"path": "/home/shahin/Benchmark_Command/Q29/command_results_4/Folder_98/generated_answer.py", "lineno": 2, "message": "TypeError: 'int' object is not iterable"}, "reprtraceback": {"reprentries": [{"type": "ReprEntry", "data": {"lines": ["    def test_list_of_ones():", "        list_of_ones = [1 for _ in range(0, (largest_index + 1) * 2)]", ">       assert gcf_two_nums(list_of_ones) == 1"], "reprfuncargs": {"args": []}, "reprlocals": null, "reprfileloc": {"path": "Q29/command_results_4/Folder_98/tests29_98_4.py", "lineno": 10, "message": ""}, "style": "long"}}, {"type": "ReprEntry", "data": {"lines": ["    def gcf_two_nums(nums):", ">       return max(list(set(nums[0]) & set(nums[9])), key=lambda x: x)", "E       TypeError: 'int' object is not iterable"], "reprfuncargs": {"args": [["nums", "[1, 1, 1, 1, 1, 1, ...]"]]}, "reprlocals": null, "reprfileloc": {"path": "Q29/command_results_4/Folder_98/generated_answer.py", "lineno": 2, "message": "TypeError"}, "style": "long"}}], "extraline": null, "style": "long"}, "sections": [], "chain": [[{"reprentries": [{"type": "ReprEntry", "data": {"lines": ["    def test_list_of_ones():", "        list_of_ones = [1 for _ in range(0, (largest_index + 1) * 2)]", ">       assert gcf_two_nums(list_of_ones) == 1"], "reprfuncargs": {"args": []}, "reprlocals": null, "reprfileloc": {"path": "Q29/command_results_4/Folder_98/tests29_98_4.py", "lineno": 10, "message": ""}, "style": "long"}}, {"type": "ReprEntry", "data": {"lines": ["    def gcf_two_nums(nums):", ">       return max(list(set(nums[0]) & set(nums[9])), key=lambda x: x)", "E       TypeError: 'int' object is not iterable"], "reprfuncargs": {"args": [["nums", "[1, 1, 1, 1, 1, 1, ...]"]]}, "reprlocals": null, "reprfileloc": {"path": "Q29/command_results_4/Folder_98/generated_answer.py", "lineno": 2, "message": "TypeError"}, "style": "long"}}], "extraline": null, "style": "long"}, {"path": "/home/shahin/Benchmark_Command/Q29/command_results_4/Folder_98/generated_answer.py", "lineno": 2, "message": "TypeError: 'int' object is not iterable"}, null]]}, "when": "call", "user_properties": [], "sections": [], "duration": 0.0001362309994874522, "extra": [], "$report_type": "TestReport", "item_index": 0, "worker_id": "gw0", "testrun_uid": "a8ecadee210e4e3190a9d4ede21af223", "node": "<WorkerController gw0>"}
{"exitstatus": 2, "$report_type": "SessionFinish"}
