{"pytest_version": "7.2.2", "$report_type": "SessionStart"}
{"nodeid": "tests42_1_4.py::test_list_of_primes", "location": ["tests42_1_4.py", 4, "test_list_of_primes"], "keywords": {"test_list_of_primes": 1, "tests42_1_4.py": 1, "Folder_1": 1}, "outcome": "passed", "longrepr": null, "when": "setup", "user_properties": [], "sections": [], "duration": 0.00014675099737360142, "$report_type": "TestReport", "item_index": 0, "worker_id": "gw0", "testrun_uid": "8b6e50bd841b48419a5e737122da41db", "node": "<WorkerController gw0>"}
{"nodeid": "tests42_1_4.py::test_list_of_tens", "location": ["tests42_1_4.py", 15, "test_list_of_tens"], "keywords": {"test_list_of_tens": 1, "tests42_1_4.py": 1, "Folder_1": 1}, "outcome": "passed", "longrepr": null, "when": "setup", "user_properties": [], "sections": [], "duration": 0.00022479999825009145, "$report_type": "TestReport", "item_index": 2, "worker_id": "gw1", "testrun_uid": "8b6e50bd841b48419a5e737122da41db", "node": "<WorkerController gw1>"}
{"nodeid": "tests42_1_4.py::test_list_of_primes", "location": ["tests42_1_4.py", 4, "test_list_of_primes"], "keywords": {"test_list_of_primes": 1, "tests42_1_4.py": 1, "Folder_1": 1}, "outcome": "failed", "longrepr": {"reprcrash": {"path": "/home/shahin/Benchmark_Command/Q42/command_results_4/Folder_1/generated_answer.py", "lineno": 2, "message": "AttributeError: 'int' object has no attribute 'factors'"}, "reprtraceback": {"reprentries": [{"type": "ReprEntry", "data": {"lines": ["    def test_list_of_primes():", "        for n in [2, 3, 5, 7, 11, 13, 17]:", "            list_of_primes = [n for _ in range((85 + 1) * 10)]", ">           assert prime_factors(list_of_primes) == {n}"], "reprfuncargs": {"args": []}, "reprlocals": null, "reprfileloc": {"path": "Q42/command_results_4/Folder_1/tests42_1_4.py", "lineno": 8, "message": ""}, "style": "long"}}, {"type": "ReprEntry", "data": {"lines": ["    def prime_factors(nums):", ">       return set(nums[85].factors())", "E       AttributeError: 'int' object has no attribute 'factors'"], "reprfuncargs": {"args": [["nums", "[2, 2, 2, 2, 2, 2, ...]"]]}, "reprlocals": null, "reprfileloc": {"path": "Q42/command_results_4/Folder_1/generated_answer.py", "lineno": 2, "message": "AttributeError"}, "style": "long"}}], "extraline": null, "style": "long"}, "sections": [], "chain": [[{"reprentries": [{"type": "ReprEntry", "data": {"lines": ["    def test_list_of_primes():", "        for n in [2, 3, 5, 7, 11, 13, 17]:", "            list_of_primes = [n for _ in range((85 + 1) * 10)]", ">           assert prime_factors(list_of_primes) == {n}"], "reprfuncargs": {"args": []}, "reprlocals": null, "reprfileloc": {"path": "Q42/command_results_4/Folder_1/tests42_1_4.py", "lineno": 8, "message": ""}, "style": "long"}}, {"type": "ReprEntry", "data": {"lines": ["    def prime_factors(nums):", ">       return set(nums[85].factors())", "E       AttributeError: 'int' object has no attribute 'factors'"], "reprfuncargs": {"args": [["nums", "[2, 2, 2, 2, 2, 2, ...]"]]}, "reprlocals": null, "reprfileloc": {"path": "Q42/command_results_4/Folder_1/generated_answer.py", "lineno": 2, "message": "AttributeError"}, "style": "long"}}], "extraline": null, "style": "long"}, {"path": "/home/shahin/Benchmark_Command/Q42/command_results_4/Folder_1/generated_answer.py", "lineno": 2, "message": "AttributeError: 'int' object has no attribute 'factors'"}, null]]}, "when": "call", "user_properties": [], "sections": [], "duration": 0.00015380400145659223, "extra": [], "$report_type": "TestReport", "item_index": 0, "worker_id": "gw0", "testrun_uid": "8b6e50bd841b48419a5e737122da41db", "node": "<WorkerController gw0>"}
{"exitstatus": 2, "$report_type": "SessionFinish"}
