{"pytest_version": "7.4.3", "$report_type": "SessionStart"}
{"nodeid": "tests46_11_1.py::test_list_of_prime_numbers", "location": ["tests46_11_1.py", 18, "test_list_of_prime_numbers"], "keywords": {"test_list_of_prime_numbers": 1, "tests46_11_1.py": 1, "Folder_11": 1}, "outcome": "passed", "longrepr": null, "when": "setup", "user_properties": [], "sections": [], "duration": 0.00012616906315088272, "start": 1701607080.5155964, "stop": 1701607080.515723, "$report_type": "TestReport", "item_index": 2, "worker_id": "gw1", "testrun_uid": "0918efd811914c4087b9618731b4a9b4", "node": "<WorkerController gw1>"}
{"nodeid": "tests46_11_1.py::test_list_of_ones", "location": ["tests46_11_1.py", 7, "test_list_of_ones"], "keywords": {"test_list_of_ones": 1, "tests46_11_1.py": 1, "Folder_11": 1}, "outcome": "passed", "longrepr": null, "when": "setup", "user_properties": [], "sections": [], "duration": 0.00017768307588994503, "start": 1701607080.515774, "stop": 1701607080.5159526, "$report_type": "TestReport", "item_index": 0, "worker_id": "gw0", "testrun_uid": "0918efd811914c4087b9618731b4a9b4", "node": "<WorkerController gw0>"}
{"nodeid": "tests46_11_1.py::test_list_of_prime_numbers", "location": ["tests46_11_1.py", 18, "test_list_of_prime_numbers"], "keywords": {"test_list_of_prime_numbers": 1, "tests46_11_1.py": 1, "Folder_11": 1}, "outcome": "failed", "longrepr": {"reprcrash": {"path": "/data/CodeLlama_13B/Q46/codellama_results_1/Folder_11/generated_answer.py", "lineno": 6, "message": "RecursionError: maximum recursion depth exceeded while calling a Python object"}, "reprtraceback": {"reprentries": [{"type": "ReprEntry", "data": {"lines": ["    def test_list_of_prime_numbers():", "        primes_list = [2, 3, 5, 7, 11] * (largest_index + 1)", "        if primes_list[37] == primes_list[30] and primes_list[30] == primes_list[48]:", "            assert gcf_three_nums(primes_list) == primes_list[37]", "        else:", ">           assert gcf_three_nums(primes_list) == 1"], "reprfuncargs": {"args": []}, "reprlocals": null, "reprfileloc": {"path": "Q46/codellama_results_1/Folder_11/tests46_11_1.py", "lineno": 24, "message": ""}, "style": "long"}}, {"type": "ReprEntry", "data": {"lines": ["    return find_gcf([numbers[37], numbers[30], numbers[48]])"], "reprfuncargs": null, "reprlocals": null, "reprfileloc": {"path": "Q46/codellama_results_1/Folder_11/generated_answer.py", "lineno": 3, "message": "in gcf_three_nums"}, "style": "short"}}, {"type": "ReprEntry", "data": {"lines": ["    return find_gcf([numbers[0], *numbers[1:]])"], "reprfuncargs": null, "reprlocals": null, "reprfileloc": {"path": "Q46/codellama_results_1/Folder_11/generated_answer.py", "lineno": 9, "message": "in find_gcf"}, "style": "short"}}, {"type": "ReprEntry", "data": {"lines": ["    return find_gcf([numbers[0], *numbers[1:]])", "E   RecursionError: maximum recursion depth exceeded while calling a Python object"], "reprfuncargs": null, "reprlocals": null, "reprfileloc": {"path": "Q46/codellama_results_1/Folder_11/generated_answer.py", "lineno": 9, "message": "in find_gcf"}, "style": "short"}}], "extraline": "!!! Recursion detected (same locals & position)", "style": "long"}, "sections": [], "chain": [[{"reprentries": [{"type": "ReprEntry", "data": {"lines": ["    def test_list_of_prime_numbers():", "        primes_list = [2, 3, 5, 7, 11] * (largest_index + 1)", "        if primes_list[37] == primes_list[30] and primes_list[30] == primes_list[48]:", "            assert gcf_three_nums(primes_list) == primes_list[37]", "        else:", ">           assert gcf_three_nums(primes_list) == 1"], "reprfuncargs": {"args": []}, "reprlocals": null, "reprfileloc": {"path": "Q46/codellama_results_1/Folder_11/tests46_11_1.py", "lineno": 24, "message": ""}, "style": "long"}}, {"type": "ReprEntry", "data": {"lines": ["    return find_gcf([numbers[37], numbers[30], numbers[48]])"], "reprfuncargs": null, "reprlocals": null, "reprfileloc": {"path": "Q46/codellama_results_1/Folder_11/generated_answer.py", "lineno": 3, "message": "in gcf_three_nums"}, "style": "short"}}, {"type": "ReprEntry", "data": {"lines": ["    return find_gcf([numbers[0], *numbers[1:]])"], "reprfuncargs": null, "reprlocals": null, "reprfileloc": {"path": "Q46/codellama_results_1/Folder_11/generated_answer.py", "lineno": 9, "message": "in find_gcf"}, "style": "short"}}, {"type": "ReprEntry", "data": {"lines": ["    return find_gcf([numbers[0], *numbers[1:]])", "E   RecursionError: maximum recursion depth exceeded while calling a Python object"], "reprfuncargs": null, "reprlocals": null, "reprfileloc": {"path": "Q46/codellama_results_1/Folder_11/generated_answer.py", "lineno": 9, "message": "in find_gcf"}, "style": "short"}}], "extraline": "!!! Recursion detected (same locals & position)", "style": "long"}, {"path": "/data/CodeLlama_13B/Q46/codellama_results_1/Folder_11/generated_answer.py", "lineno": 6, "message": "RecursionError: maximum recursion depth exceeded while calling a Python object"}, null]]}, "when": "call", "user_properties": [], "sections": [], "duration": 0.0009080700110644102, "start": 1701607080.515955, "stop": 1701607080.5168638, "extras": [], "$report_type": "TestReport", "item_index": 2, "worker_id": "gw1", "testrun_uid": "0918efd811914c4087b9618731b4a9b4", "node": "<WorkerController gw1>"}
{"exitstatus": 2, "$report_type": "SessionFinish"}
