{"pytest_version": "7.4.3", "$report_type": "SessionStart"}
{"nodeid": "tests42_29_3.py::test_list_of_tens", "location": ["tests42_29_3.py", 15, "test_list_of_tens"], "keywords": {"test_list_of_tens": 1, "tests42_29_3.py": 1, "Folder_29": 1}, "outcome": "passed", "longrepr": null, "when": "setup", "user_properties": [], "sections": [], "duration": 0.00010341400047764182, "start": 1700330387.327435, "stop": 1700330387.327539, "$report_type": "TestReport", "item_index": 2, "worker_id": "gw1", "testrun_uid": "c990b4c0a5534d92957c4c4d17c95fd8", "node": "<WorkerController gw1>"}
{"nodeid": "tests42_29_3.py::test_list_of_primes", "location": ["tests42_29_3.py", 4, "test_list_of_primes"], "keywords": {"test_list_of_primes": 1, "tests42_29_3.py": 1, "Folder_29": 1}, "outcome": "passed", "longrepr": null, "when": "setup", "user_properties": [], "sections": [], "duration": 0.0001380520116072148, "start": 1700330387.3276339, "stop": 1700330387.3277729, "$report_type": "TestReport", "item_index": 0, "worker_id": "gw0", "testrun_uid": "c990b4c0a5534d92957c4c4d17c95fd8", "node": "<WorkerController gw0>"}
{"nodeid": "tests42_29_3.py::test_list_of_tens", "location": ["tests42_29_3.py", 15, "test_list_of_tens"], "keywords": {"test_list_of_tens": 1, "tests42_29_3.py": 1, "Folder_29": 1}, "outcome": "failed", "longrepr": {"reprcrash": {"path": "/data/CodeLlama_13B/Q42/codellama_results_3/Folder_29/generated_answer.py", "lineno": 3, "message": "AttributeError: 'int' object has no attribute 'prime_factors'"}, "reprtraceback": {"reprentries": [{"type": "ReprEntry", "data": {"lines": ["    def test_list_of_tens():", "        list_of_tens = [10] * (19 + 100)", ">       assert prime_factors(list_of_tens) == {2,5}"], "reprfuncargs": {"args": []}, "reprlocals": null, "reprfileloc": {"path": "Q42/codellama_results_3/Folder_29/tests42_29_3.py", "lineno": 18, "message": ""}, "style": "long"}}, {"type": "ReprEntry", "data": {"lines": ["    def prime_factors(my_list):", ">       return set([x for x in my_list[19].prime_factors()])", "E       AttributeError: 'int' object has no attribute 'prime_factors'"], "reprfuncargs": {"args": [["my_list", "[10, 10, 10, 10, 10, 10, ...]"]]}, "reprlocals": null, "reprfileloc": {"path": "Q42/codellama_results_3/Folder_29/generated_answer.py", "lineno": 3, "message": "AttributeError"}, "style": "long"}}], "extraline": null, "style": "long"}, "sections": [], "chain": [[{"reprentries": [{"type": "ReprEntry", "data": {"lines": ["    def test_list_of_tens():", "        list_of_tens = [10] * (19 + 100)", ">       assert prime_factors(list_of_tens) == {2,5}"], "reprfuncargs": {"args": []}, "reprlocals": null, "reprfileloc": {"path": "Q42/codellama_results_3/Folder_29/tests42_29_3.py", "lineno": 18, "message": ""}, "style": "long"}}, {"type": "ReprEntry", "data": {"lines": ["    def prime_factors(my_list):", ">       return set([x for x in my_list[19].prime_factors()])", "E       AttributeError: 'int' object has no attribute 'prime_factors'"], "reprfuncargs": {"args": [["my_list", "[10, 10, 10, 10, 10, 10, ...]"]]}, "reprlocals": null, "reprfileloc": {"path": "Q42/codellama_results_3/Folder_29/generated_answer.py", "lineno": 3, "message": "AttributeError"}, "style": "long"}}], "extraline": null, "style": "long"}, {"path": "/data/CodeLlama_13B/Q42/codellama_results_3/Folder_29/generated_answer.py", "lineno": 3, "message": "AttributeError: 'int' object has no attribute 'prime_factors'"}, null]]}, "when": "call", "user_properties": [], "sections": [], "duration": 0.00010104599641636014, "start": 1700330387.327705, "stop": 1700330387.3278062, "extras": [], "$report_type": "TestReport", "item_index": 2, "worker_id": "gw1", "testrun_uid": "c990b4c0a5534d92957c4c4d17c95fd8", "node": "<WorkerController gw1>"}
{"exitstatus": 2, "$report_type": "SessionFinish"}
