{
  "parameter(s)": [
    841,
    804
  ],
  "test_list_of_prime_numbers": [
    "passed",
    "",
    0.00022
  ],
  "test_list_of_ones": [
    "failed",
    "RecursionError: maximum recursion depth exceeded while calling a Python object",
    0.01159
  ]
}