{"pytest_version": "7.2.2", "$report_type": "SessionStart"}
{"nodeid": "tests11_56_1.py::test_all_zero_range", "location": ["tests11_56_1.py", 14, "test_all_zero_range"], "keywords": {"test_all_zero_range": 1, "tests11_56_1.py": 1, "Folder_56": 1}, "outcome": "passed", "longrepr": null, "when": "setup", "user_properties": [], "sections": [], "duration": 0.0001698440028121695, "$report_type": "TestReport", "item_index": 2, "worker_id": "gw1", "testrun_uid": "884e71bd313e40259f284023b871a52e", "node": "<WorkerController gw1>"}
{"nodeid": "tests11_56_1.py::test_largest_is_in_range", "location": ["tests11_56_1.py", 3, "test_largest_is_in_range"], "keywords": {"test_largest_is_in_range": 1, "tests11_56_1.py": 1, "Folder_56": 1}, "outcome": "passed", "longrepr": null, "when": "setup", "user_properties": [], "sections": [], "duration": 0.00021763599943369627, "$report_type": "TestReport", "item_index": 0, "worker_id": "gw0", "testrun_uid": "884e71bd313e40259f284023b871a52e", "node": "<WorkerController gw0>"}
{"nodeid": "tests11_56_1.py::test_all_zero_range", "location": ["tests11_56_1.py", 14, "test_all_zero_range"], "keywords": {"test_all_zero_range": 1, "tests11_56_1.py": 1, "Folder_56": 1}, "outcome": "failed", "longrepr": {"reprcrash": {"path": "/home/shahin/Benchmark_Command_T0/Q11/command_results_1/Folder_56/generated_answer.py", "lineno": 2, "message": "ValueError: max() arg is an empty sequence"}, "reprtraceback": {"reprentries": [{"type": "ReprEntry", "data": {"lines": ["    def test_all_zero_range():", "        zero_list = [0 for _ in range(0,(0 + 1) * 5)]", ">       assert find_largest_num(zero_list) == 0"], "reprfuncargs": {"args": []}, "reprlocals": null, "reprfileloc": {"path": "Q11/command_results_1/Folder_56/tests11_56_1.py", "lineno": 17, "message": ""}, "style": "long"}}, {"type": "ReprEntry", "data": {"lines": ["    def find_largest_num(nums):", ">       return max(nums[0:0])", "E       ValueError: max() arg is an empty sequence"], "reprfuncargs": {"args": [["nums", "[0, 0, 0, 0, 0]"]]}, "reprlocals": null, "reprfileloc": {"path": "Q11/command_results_1/Folder_56/generated_answer.py", "lineno": 2, "message": "ValueError"}, "style": "long"}}], "extraline": null, "style": "long"}, "sections": [], "chain": [[{"reprentries": [{"type": "ReprEntry", "data": {"lines": ["    def test_all_zero_range():", "        zero_list = [0 for _ in range(0,(0 + 1) * 5)]", ">       assert find_largest_num(zero_list) == 0"], "reprfuncargs": {"args": []}, "reprlocals": null, "reprfileloc": {"path": "Q11/command_results_1/Folder_56/tests11_56_1.py", "lineno": 17, "message": ""}, "style": "long"}}, {"type": "ReprEntry", "data": {"lines": ["    def find_largest_num(nums):", ">       return max(nums[0:0])", "E       ValueError: max() arg is an empty sequence"], "reprfuncargs": {"args": [["nums", "[0, 0, 0, 0, 0]"]]}, "reprlocals": null, "reprfileloc": {"path": "Q11/command_results_1/Folder_56/generated_answer.py", "lineno": 2, "message": "ValueError"}, "style": "long"}}], "extraline": null, "style": "long"}, {"path": "/home/shahin/Benchmark_Command_T0/Q11/command_results_1/Folder_56/generated_answer.py", "lineno": 2, "message": "ValueError: max() arg is an empty sequence"}, null]]}, "when": "call", "user_properties": [], "sections": [], "duration": 0.00018270900181960315, "extra": [], "$report_type": "TestReport", "item_index": 2, "worker_id": "gw1", "testrun_uid": "884e71bd313e40259f284023b871a52e", "node": "<WorkerController gw1>"}
{"exitstatus": 2, "$report_type": "SessionFinish"}
