{"pytest_version": "7.2.2", "$report_type": "SessionStart"}
{"nodeid": "tests6_22_1.py::test_even_range", "location": ["tests6_22_1.py", 13, "test_even_range"], "keywords": {"test_even_range": 1, "tests6_22_1.py": 1, "Folder_22": 1}, "outcome": "passed", "longrepr": null, "when": "setup", "user_properties": [], "sections": [], "duration": 0.00012122699990868568, "$report_type": "TestReport", "item_index": 2, "worker_id": "gw1", "testrun_uid": "6af3cdd893bb4226a3e64441859870d0", "node": "<WorkerController gw1>"}
{"nodeid": "tests6_22_1.py::test_large_range", "location": ["tests6_22_1.py", 3, "test_large_range"], "keywords": {"test_large_range": 1, "tests6_22_1.py": 1, "Folder_22": 1}, "outcome": "passed", "longrepr": null, "when": "setup", "user_properties": [], "sections": [], "duration": 0.00016241399998762063, "$report_type": "TestReport", "item_index": 0, "worker_id": "gw0", "testrun_uid": "6af3cdd893bb4226a3e64441859870d0", "node": "<WorkerController gw0>"}
{"nodeid": "tests6_22_1.py::test_large_range", "location": ["tests6_22_1.py", 3, "test_large_range"], "keywords": {"test_large_range": 1, "tests6_22_1.py": 1, "Folder_22": 1}, "outcome": "failed", "longrepr": {"reprcrash": {"path": "/home/shahin/Benchmark_Command/Q6/command_results_1/Folder_22/generated_answer.py", "lineno": 2, "message": "TypeError: '<' not supported between instances of 'list' and 'int'"}, "reprtraceback": {"reprentries": [{"type": "ReprEntry", "data": {"lines": ["    def test_large_range():", "        large_list = list(range(0, 200 + 1000))", ">       assert all_neg_ints_exclusive(large_list) == []"], "reprfuncargs": {"args": []}, "reprlocals": null, "reprfileloc": {"path": "Q6/command_results_1/Folder_22/tests6_22_1.py", "lineno": 6, "message": ""}, "style": "long"}}, {"type": "ReprEntry", "data": {"lines": ["    def all_neg_ints_exclusive(lst):", ">       return lst[40:200][lst[40:200] < 0]", "E       TypeError: '<' not supported between instances of 'list' and 'int'"], "reprfuncargs": {"args": [["lst", "[0, 1, 2, 3, 4, 5, ...]"]]}, "reprlocals": null, "reprfileloc": {"path": "Q6/command_results_1/Folder_22/generated_answer.py", "lineno": 2, "message": "TypeError"}, "style": "long"}}], "extraline": null, "style": "long"}, "sections": [], "chain": [[{"reprentries": [{"type": "ReprEntry", "data": {"lines": ["    def test_large_range():", "        large_list = list(range(0, 200 + 1000))", ">       assert all_neg_ints_exclusive(large_list) == []"], "reprfuncargs": {"args": []}, "reprlocals": null, "reprfileloc": {"path": "Q6/command_results_1/Folder_22/tests6_22_1.py", "lineno": 6, "message": ""}, "style": "long"}}, {"type": "ReprEntry", "data": {"lines": ["    def all_neg_ints_exclusive(lst):", ">       return lst[40:200][lst[40:200] < 0]", "E       TypeError: '<' not supported between instances of 'list' and 'int'"], "reprfuncargs": {"args": [["lst", "[0, 1, 2, 3, 4, 5, ...]"]]}, "reprlocals": null, "reprfileloc": {"path": "Q6/command_results_1/Folder_22/generated_answer.py", "lineno": 2, "message": "TypeError"}, "style": "long"}}], "extraline": null, "style": "long"}, {"path": "/home/shahin/Benchmark_Command/Q6/command_results_1/Folder_22/generated_answer.py", "lineno": 2, "message": "TypeError: '<' not supported between instances of 'list' and 'int'"}, null]]}, "when": "call", "user_properties": [], "sections": [], "duration": 0.00017883500004245434, "extra": [], "$report_type": "TestReport", "item_index": 0, "worker_id": "gw0", "testrun_uid": "6af3cdd893bb4226a3e64441859870d0", "node": "<WorkerController gw0>"}
{"exitstatus": 2, "$report_type": "SessionFinish"}
