{"pytest_version": "7.4.3", "$report_type": "SessionStart"}
{"nodeid": "tests58_36_5.py::test_matrix_of_one_integer", "location": ["tests58_36_5.py", 18, "test_matrix_of_one_integer"], "keywords": {"test_matrix_of_one_integer": 1, "__wrapped__": 1, "tests58_36_5.py": 1, "Folder_36": 1}, "outcome": "passed", "longrepr": null, "when": "setup", "user_properties": [], "sections": [], "duration": 0.000162130017997697, "start": 1700279716.4701629, "stop": 1700279716.470326, "$report_type": "TestReport", "item_index": 0, "worker_id": "gw0", "testrun_uid": "7e0295c3e68a4e06a2307e402e4a869d", "node": "<WorkerController gw0>"}
{"nodeid": "tests58_36_5.py::test_horizontal_matrix", "location": ["tests58_36_5.py", 40, "test_horizontal_matrix"], "keywords": {"test_horizontal_matrix": 1, "__wrapped__": 1, "tests58_36_5.py": 1, "Folder_36": 1}, "outcome": "passed", "longrepr": null, "when": "setup", "user_properties": [], "sections": [], "duration": 0.0001420699991285801, "start": 1700279716.4828253, "stop": 1700279716.4829679, "$report_type": "TestReport", "item_index": 2, "worker_id": "gw1", "testrun_uid": "7e0295c3e68a4e06a2307e402e4a869d", "node": "<WorkerController gw1>"}
{"nodeid": "tests58_36_5.py::test_matrix_of_one_integer", "location": ["tests58_36_5.py", 18, "test_matrix_of_one_integer"], "keywords": {"test_matrix_of_one_integer": 1, "__wrapped__": 1, "tests58_36_5.py": 1, "Folder_36": 1}, "outcome": "failed", "longrepr": {"reprcrash": {"path": "/usr/lib/python3/dist-packages/numpy/matrixlib/defmatrix.py", "lineno": 193, "message": "IndexError: index 1 is out of bounds for axis 0 with size 1"}, "reprtraceback": {"reprentries": [{"type": "ReprEntry", "data": {"lines": ["    @ignore_warnings", "    def test_matrix_of_one_integer():", "        input_matrix = [[131]]", "        input_matrix = np.asmatrix(input_matrix)", "        if 131 == 1:", "            assert submatrix_with_n_numbers(input_matrix) == 1", "        else:", ">           assert not submatrix_with_n_numbers(input_matrix)"], "reprfuncargs": {"args": []}, "reprlocals": null, "reprfileloc": {"path": "Q58/codellama_7b_results_5/Folder_36/tests58_36_5.py", "lineno": 26, "message": ""}, "style": "long"}}, {"type": "ReprEntry", "data": {"lines": ["    if matrix[k][l] != 0:"], "reprfuncargs": null, "reprlocals": null, "reprfileloc": {"path": "Q58/codellama_7b_results_5/Folder_36/generated_answer.py", "lineno": 16, "message": "in submatrix_with_n_numbers"}, "style": "short"}}, {"type": "ReprEntry", "data": {"lines": ["    def __getitem__(self, index):", "        self._getitem = True", "    ", "        try:", ">           out = N.ndarray.__getitem__(self, index)", "E           IndexError: index 1 is out of bounds for axis 0 with size 1"], "reprfuncargs": {"args": [["self", "matrix([[131]])"], ["index", "1"]]}, "reprlocals": null, "reprfileloc": {"path": "/usr/lib/python3/dist-packages/numpy/matrixlib/defmatrix.py", "lineno": 193, "message": "IndexError"}, "style": "long"}}], "extraline": null, "style": "long"}, "sections": [], "chain": [[{"reprentries": [{"type": "ReprEntry", "data": {"lines": ["    @ignore_warnings", "    def test_matrix_of_one_integer():", "        input_matrix = [[131]]", "        input_matrix = np.asmatrix(input_matrix)", "        if 131 == 1:", "            assert submatrix_with_n_numbers(input_matrix) == 1", "        else:", ">           assert not submatrix_with_n_numbers(input_matrix)"], "reprfuncargs": {"args": []}, "reprlocals": null, "reprfileloc": {"path": "Q58/codellama_7b_results_5/Folder_36/tests58_36_5.py", "lineno": 26, "message": ""}, "style": "long"}}, {"type": "ReprEntry", "data": {"lines": ["    if matrix[k][l] != 0:"], "reprfuncargs": null, "reprlocals": null, "reprfileloc": {"path": "Q58/codellama_7b_results_5/Folder_36/generated_answer.py", "lineno": 16, "message": "in submatrix_with_n_numbers"}, "style": "short"}}, {"type": "ReprEntry", "data": {"lines": ["    def __getitem__(self, index):", "        self._getitem = True", "    ", "        try:", ">           out = N.ndarray.__getitem__(self, index)", "E           IndexError: index 1 is out of bounds for axis 0 with size 1"], "reprfuncargs": {"args": [["self", "matrix([[131]])"], ["index", "1"]]}, "reprlocals": null, "reprfileloc": {"path": "/usr/lib/python3/dist-packages/numpy/matrixlib/defmatrix.py", "lineno": 193, "message": "IndexError"}, "style": "long"}}], "extraline": null, "style": "long"}, {"path": "/usr/lib/python3/dist-packages/numpy/matrixlib/defmatrix.py", "lineno": 193, "message": "IndexError: index 1 is out of bounds for axis 0 with size 1"}, null]]}, "when": "call", "user_properties": [], "sections": [], "duration": 0.00023532300838269293, "start": 1700279716.4705932, "stop": 1700279716.4708292, "extras": [], "$report_type": "TestReport", "item_index": 0, "worker_id": "gw0", "testrun_uid": "7e0295c3e68a4e06a2307e402e4a869d", "node": "<WorkerController gw0>"}
{"exitstatus": 2, "$report_type": "SessionFinish"}
