{"pytest_version": "7.4.3", "$report_type": "SessionStart"}
{"nodeid": "", "outcome": "passed", "longrepr": null, "result": null, "sections": [], "$report_type": "CollectReport"}
{"nodeid": "tests27_84_2.py", "outcome": "passed", "longrepr": null, "result": null, "sections": [], "$report_type": "CollectReport"}
{"nodeid": "tests27_84_2.py::test_presence_of_inserted_element", "location": ["tests27_84_2.py", 4, "test_presence_of_inserted_element"], "keywords": {"test_presence_of_inserted_element": 1, "tests27_84_2.py": 1, "Folder_84": 1}, "outcome": "passed", "longrepr": null, "when": "setup", "user_properties": [], "sections": [], "duration": 0.00021085294429212809, "start": 1701648338.3650866, "stop": 1701648338.365299, "$report_type": "TestReport"}
{"nodeid": "tests27_84_2.py::test_presence_of_inserted_element", "location": ["tests27_84_2.py", 4, "test_presence_of_inserted_element"], "keywords": {"test_presence_of_inserted_element": 1, "tests27_84_2.py": 1, "Folder_84": 1}, "outcome": "failed", "longrepr": {"reprcrash": {"path": "/data/Benchmark_GPT3_5/Q27/gpt_3_5_turbo_results_2/Folder_84/generated_answer.py", "lineno": 3, "message": "ValueError: 183 is not in list"}, "reprtraceback": {"reprentries": [{"type": "ReprEntry", "data": {"lines": ["    def test_presence_of_inserted_element():", "        initial_list = [set() for i in range((183 + 1) * 2)]", ">       returned_list = insert_after_index(initial_list)"], "reprfuncargs": {"args": []}, "reprlocals": null, "reprfileloc": {"path": "Q27/gpt_3_5_turbo_results_2/Folder_84/tests27_84_2.py", "lineno": 7, "message": ""}, "style": "long"}}, {"type": "ReprEntry", "data": {"lines": ["    def insert_after_index(lst):", ">       index_183 = lst.index(183)", "E       ValueError: 183 is not in list"], "reprfuncargs": {"args": [["lst", "[set(), set(), set(), set(), set(), set(), ...]"]]}, "reprlocals": null, "reprfileloc": {"path": "Q27/gpt_3_5_turbo_results_2/Folder_84/generated_answer.py", "lineno": 3, "message": "ValueError"}, "style": "long"}}], "extraline": null, "style": "long"}, "sections": [], "chain": [[{"reprentries": [{"type": "ReprEntry", "data": {"lines": ["    def test_presence_of_inserted_element():", "        initial_list = [set() for i in range((183 + 1) * 2)]", ">       returned_list = insert_after_index(initial_list)"], "reprfuncargs": {"args": []}, "reprlocals": null, "reprfileloc": {"path": "Q27/gpt_3_5_turbo_results_2/Folder_84/tests27_84_2.py", "lineno": 7, "message": ""}, "style": "long"}}, {"type": "ReprEntry", "data": {"lines": ["    def insert_after_index(lst):", ">       index_183 = lst.index(183)", "E       ValueError: 183 is not in list"], "reprfuncargs": {"args": [["lst", "[set(), set(), set(), set(), set(), set(), ...]"]]}, "reprlocals": null, "reprfileloc": {"path": "Q27/gpt_3_5_turbo_results_2/Folder_84/generated_answer.py", "lineno": 3, "message": "ValueError"}, "style": "long"}}], "extraline": null, "style": "long"}, {"path": "/data/Benchmark_GPT3_5/Q27/gpt_3_5_turbo_results_2/Folder_84/generated_answer.py", "lineno": 3, "message": "ValueError: 183 is not in list"}, null]]}, "when": "call", "user_properties": [], "sections": [], "duration": 0.0003180858911946416, "start": 1701648338.3655102, "stop": 1701648338.3658292, "extras": [], "$report_type": "TestReport"}
{"nodeid": "tests27_84_2.py::test_presence_of_inserted_element", "location": ["tests27_84_2.py", 4, "test_presence_of_inserted_element"], "keywords": {"test_presence_of_inserted_element": 1, "tests27_84_2.py": 1, "Folder_84": 1}, "outcome": "passed", "longrepr": null, "when": "teardown", "user_properties": [], "sections": [], "duration": 0.0002538589760661125, "start": 1701648338.371726, "stop": 1701648338.3719811, "$report_type": "TestReport"}
{"exitstatus": 1, "$report_type": "SessionFinish"}
