{"pytest_version": "7.2.2", "$report_type": "SessionStart"}
{"nodeid": "tests11_56_5.py::test_all_zero_range", "location": ["tests11_56_5.py", 14, "test_all_zero_range"], "keywords": {"test_all_zero_range": 1, "tests11_56_5.py": 1, "Folder_56": 1}, "outcome": "passed", "longrepr": null, "when": "setup", "user_properties": [], "sections": [], "duration": 0.00011566100147319958, "$report_type": "TestReport", "item_index": 2, "worker_id": "gw1", "testrun_uid": "bb64f69406894c60936532ddf1e93e0c", "node": "<WorkerController gw1>"}
{"nodeid": "tests11_56_5.py::test_largest_is_in_range", "location": ["tests11_56_5.py", 3, "test_largest_is_in_range"], "keywords": {"test_largest_is_in_range": 1, "tests11_56_5.py": 1, "Folder_56": 1}, "outcome": "passed", "longrepr": null, "when": "setup", "user_properties": [], "sections": [], "duration": 0.00013908600521972403, "$report_type": "TestReport", "item_index": 0, "worker_id": "gw0", "testrun_uid": "bb64f69406894c60936532ddf1e93e0c", "node": "<WorkerController gw0>"}
{"nodeid": "tests11_56_5.py::test_largest_is_in_range", "location": ["tests11_56_5.py", 3, "test_largest_is_in_range"], "keywords": {"test_largest_is_in_range": 1, "tests11_56_5.py": 1, "Folder_56": 1}, "outcome": "failed", "longrepr": {"reprcrash": {"path": "/home/shahin/Benchmark_Command_T0/Q11/command_results_5/Folder_56/generated_answer.py", "lineno": 2, "message": "ValueError: max() arg is an empty sequence"}, "reprtraceback": {"reprentries": [{"type": "ReprEntry", "data": {"lines": ["    def test_largest_is_in_range():", "        large_list = [i for i in range(0,(0 + 1) * 1000)]", ">       assert find_largest_num(large_list) in large_list"], "reprfuncargs": {"args": []}, "reprlocals": null, "reprfileloc": {"path": "Q11/command_results_5/Folder_56/tests11_56_5.py", "lineno": 6, "message": ""}, "style": "long"}}, {"type": "ReprEntry", "data": {"lines": ["    def find_largest_num(nums):", ">       return max(nums[0:0])", "E       ValueError: max() arg is an empty sequence"], "reprfuncargs": {"args": [["nums", "[0, 1, 2, 3, 4, 5, ...]"]]}, "reprlocals": null, "reprfileloc": {"path": "Q11/command_results_5/Folder_56/generated_answer.py", "lineno": 2, "message": "ValueError"}, "style": "long"}}], "extraline": null, "style": "long"}, "sections": [], "chain": [[{"reprentries": [{"type": "ReprEntry", "data": {"lines": ["    def test_largest_is_in_range():", "        large_list = [i for i in range(0,(0 + 1) * 1000)]", ">       assert find_largest_num(large_list) in large_list"], "reprfuncargs": {"args": []}, "reprlocals": null, "reprfileloc": {"path": "Q11/command_results_5/Folder_56/tests11_56_5.py", "lineno": 6, "message": ""}, "style": "long"}}, {"type": "ReprEntry", "data": {"lines": ["    def find_largest_num(nums):", ">       return max(nums[0:0])", "E       ValueError: max() arg is an empty sequence"], "reprfuncargs": {"args": [["nums", "[0, 1, 2, 3, 4, 5, ...]"]]}, "reprlocals": null, "reprfileloc": {"path": "Q11/command_results_5/Folder_56/generated_answer.py", "lineno": 2, "message": "ValueError"}, "style": "long"}}], "extraline": null, "style": "long"}, {"path": "/home/shahin/Benchmark_Command_T0/Q11/command_results_5/Folder_56/generated_answer.py", "lineno": 2, "message": "ValueError: max() arg is an empty sequence"}, null]]}, "when": "call", "user_properties": [], "sections": [], "duration": 0.00015721999807283282, "extra": [], "$report_type": "TestReport", "item_index": 0, "worker_id": "gw0", "testrun_uid": "bb64f69406894c60936532ddf1e93e0c", "node": "<WorkerController gw0>"}
{"exitstatus": 2, "$report_type": "SessionFinish"}
